{
  parserClass="za.co.svenlange.intellij.xtend.parser.XtendParser"
  stubParserClass="za.co.svenlange.intellij.xtend.parser.GeneratedParserUtilBase"
 
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
 
  psiClassPrefix="Xtend"
  psiImplClassSuffix="Impl"
  psiPackage="za.co.svenlange.intellij.xtend.psi"
  psiImplPackage="za.co.svenlange.intellij.xtend.psi.impl"
 
  elementTypeHolderClass="za.co.svenlange.intellij.xtend.psi.XtendTypes"
  elementTypeClass="za.co.svenlange.intellij.xtend.psi.XtendElementType"
  tokenTypeClass="za.co.svenlange.intellij.xtend.psi.XtendTokenType"
}
 
simpleFile ::= item_*
 
private item_ ::= (property|COMMENT|CRLF)
 
property ::= (KEY? SEPARATOR VALUE?) | KEY