{
  classHeader="header.txt"
  parserClass="za.co.svenlange.intellij.xtend.parser.XtendParser"
  stubParserClass="za.co.svenlange.intellij.xtend.parser.GeneratedParserUtilBase"
 
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
 
  psiClassPrefix="Xtend"
  psiImplClassSuffix="Impl"
  psiPackage="za.co.svenlange.intellij.xtend.psi"
  psiImplPackage="za.co.svenlange.intellij.xtend.psi"
 
  elementTypeHolderClass="za.co.svenlange.intellij.xtend.psi.XtendTypes"
  elementTypeClass="za.co.svenlange.intellij.xtend.psi.XtendElementType"
  tokenTypeClass="za.co.svenlange.intellij.xtend.psi.XtendTokenType"
}
 
XtendFile ::= (Buchstaben|Keyword|String|IntegerLiteral|Comment|LineTerminator)